#!/usr/bin/env perl
use strict;
use warnings;

use FindBin qw($RealBin);
use lib "$RealBin/../lib";

use Test::More;

use_ok 'App::Arcanum::Logger';
use_ok 'App::Arcanum::Config';
use_ok 'App::Arcanum::Detector::Base';
use_ok 'App::Arcanum::Detector::Email';
use_ok 'App::Arcanum::Detector::SSN';
use_ok 'App::Arcanum::Detector::CreditCard';
use_ok 'App::Arcanum::Detector::Phone';
use_ok 'App::Arcanum::Detector::Name';
use_ok 'App::Arcanum::Detector::IPAddress';
use_ok 'App::Arcanum::Detector::MACAddress';
use_ok 'App::Arcanum::Detector::DateOfBirth';
use_ok 'App::Arcanum::Detector::PassportNumber';
use_ok 'App::Arcanum::Detector::NIN';
use_ok 'App::Arcanum::Detector::SIN';
use_ok 'App::Arcanum::Detector::TFN';
use_ok 'App::Arcanum::Detector::IBAN';
use_ok 'App::Arcanum::Detector::VIN';
use_ok 'App::Arcanum::Detector::MedicalID';
use_ok 'App::Arcanum::Detector::NationalID';
use_ok 'App::Arcanum::Detector::PhysicalAddress';
use_ok 'App::Arcanum::Detector::CalendarEvent';
use_ok 'App::Arcanum::Detector::FullEmail';
use_ok 'App::Arcanum::Detector::Secrets';
use_ok 'App::Arcanum::FileClassifier';
use_ok 'App::Arcanum::Format::Base';
use_ok 'App::Arcanum::Format::PlainText';
use_ok 'App::Arcanum::Format::CSV';
use_ok 'App::Arcanum::Format::JSON';
use_ok 'App::Arcanum::Format::YAML';
use_ok 'App::Arcanum::Format::LDIF';
use_ok 'App::Arcanum::Format::MongoDB';
use_ok 'App::Arcanum::Format::Spreadsheet';
use_ok 'App::Arcanum::Format::ICS';
use_ok 'App::Arcanum::Format::Mbox';
use_ok 'App::Arcanum::Format::Sieve';
use_ok 'App::Arcanum::ArchiveHandler';
use_ok 'App::Arcanum::Remediation::Base';
use_ok 'App::Arcanum::Remediation::Deleter';
use_ok 'App::Arcanum::Remediation::Redactor';
use_ok 'App::Arcanum::Remediation::Quarantine';
use_ok 'App::Arcanum::Remediation::Encryptor';
use_ok 'App::Arcanum::Remediation::GitRewriter';
use_ok 'App::Arcanum::Notification::Base';
use_ok 'App::Arcanum::Notification::Email';
use_ok 'App::Arcanum::Notification::Webhook';
use_ok 'App::Arcanum::Notification::GitHub';
use_ok 'App::Arcanum::Notification::GitLab';
use_ok 'App::Arcanum::Notification::Bitbucket';
use_ok 'App::Arcanum::Notification::Dispatcher';
use_ok 'App::Arcanum::Report::Text';
use_ok 'App::Arcanum::Report::JSON';
use_ok 'App::Arcanum::Report::HTML';
use_ok 'App::Arcanum::Report::ComplianceMap';
use_ok 'App::Arcanum::Detector::Plugin';
use_ok 'App::Arcanum::Detector::CommandLinePII';
use_ok 'App::Arcanum::SpecialFiles';
use_ok 'App::Arcanum::Tombstone';
use_ok 'App::Arcanum';

done_testing();
